import {
  cpSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import { execa } from "execa";

import { installAdapter } from "../adapter/install.js";
import { initializeHarnessTrust } from "../harness/harness.js";
import { fetchTemplate, verifyTemplateTree } from "../harness/template.js";
import { generateGatePreset } from "../state/gate-presets.js";
import { createRunPlan } from "../state/plans.js";
import { ensurePaperRunDir, writeGatePolicy, writeRunState, writeStageHistory } from "../state/store.js";
import type { RunState } from "../state/schema.js";
import { startCommand, type StartOptions } from "./start.js";
import { DEFAULT_TEMPLATE_VERSION, GIT, MODES, PAPER_RUN_DIR } from "../utils/constants.js";
import type { Mode } from "../utils/constants.js";
import { commitCheckpoint, createRunBranch, generateRunId } from "../utils/git.js";
import { PaperRunError } from "../utils/errors.js";
import { log, printKeyValues } from "../utils/logger.js";
import { isEmptyDir } from "../utils/paths.js";
import { reviewTreeDigest } from "../utils/review-integrity.js";

const EXCLUDED_SOURCE_ENTRIES = new Set([".git", PAPER_RUN_DIR]);

export interface ReviewOptions extends StartOptions {
  output?: string;
  entry?: string;
  mode?: string;
  template?: string;
  prepareOnly?: boolean;
}

export interface ReviewWorkspaceResult {
  workspace: string;
  entrypoint: string;
  files: string[];
}

export interface ReviewSourceInspection {
  entrypoint: string;
  sourceGraph: string[];
  bibliography: string[];
  figures: string[];
  tables: string[];
  styles: string[];
  buildFiles: string[];
  evidenceFiles: string[];
}

export async function reviewCommand(source: string, opts: ReviewOptions): Promise<void> {
  if (opts.headless && (opts.mode ?? "collaborative") === "collaborative") {
    throw new PaperRunError("Headless standalone review requires autonomous mode.", {
      hint: "Pass --mode autonomous, or omit --headless to review the gate in the TUI.",
    });
  }
  const prepared = await prepareReviewWorkspace(source, opts);
  reportPrepared(prepared);
  if (opts.prepareOnly) return;

  const previous = process.cwd();
  try {
    process.chdir(prepared.workspace);
    await startCommand({
      ...(opts.headless !== undefined ? { headless: opts.headless } : {}),
      ...(opts.model !== undefined ? { model: opts.model } : {}),
      ...(opts.variant !== undefined ? { variant: opts.variant } : {}),
      ...(opts.port !== undefined ? { port: opts.port } : {}),
      ...(opts.stageTimeoutMultiplier !== undefined
        ? { stageTimeoutMultiplier: opts.stageTimeoutMultiplier }
        : {}),
    });
  } finally {
    process.chdir(previous);
  }
}

export async function prepareReviewWorkspace(
  source: string,
  opts: Pick<ReviewOptions, "output" | "entry" | "mode" | "template" | "model"> = {},
): Promise<ReviewWorkspaceResult> {
  const sourceDir = resolve(source);
  assertSourceDirectory(sourceDir);
  const workspace = resolve(opts.output ?? `${sourceDir}-review`);
  assertWorkspaceUsable(sourceDir, workspace);
  const mode = parseMode(opts.mode ?? "collaborative");
  const version = opts.template ?? DEFAULT_TEMPLATE_VERSION;
  const entrypoint = detectEntrypoint(sourceDir, opts.entry);
  const createdWorkspace = !existsSync(workspace);

  try {
    log.step(`Preparing an isolated review workspace at ${workspace}`);
    await fetchTemplate({ targetDir: workspace, version, source: "local" });
    const missing = verifyTemplateTree(workspace);
    if (missing.length > 0) throw new PaperRunError(`The fetched template is missing expected files: ${missing.join(", ")}`);

    const paperDir = join(workspace, "paper");
    rmSync(paperDir, { recursive: true, force: true });
    mkdirSync(paperDir, { recursive: true });
    const files = copyPaperSource(sourceDir, paperDir);
    const relativeEntry = toPosix(relative(sourceDir, entrypoint));
    if (relativeEntry !== "main.tex") {
      writeFileSync(join(paperDir, "main.tex"), `% Generated by paper-run for isolated review.\n\\input{${relativeEntry}}\n`);
      files.push("main.tex");
    }
    const inspection = inspectReviewSource(sourceDir, relativeEntry, files);
    writeReviewContext(workspace, basenamePosix(toPosix(sourceDir)), inspection, files, reviewTreeDigest(workspace));
    await initializeReviewRepository(workspace, version, mode, opts.model);
    return { workspace, entrypoint: relativeEntry, files: files.sort() };
  } catch (error) {
    if (createdWorkspace && existsSync(workspace)) rmSync(workspace, { recursive: true, force: true });
    throw error;
  }
}

function assertSourceDirectory(sourceDir: string): void {
  if (!existsSync(sourceDir) || !statSync(sourceDir).isDirectory() || lstatSync(sourceDir).isSymbolicLink()) {
    throw new PaperRunError(`Paper source is not a directory: ${sourceDir}`);
  }
}

function assertWorkspaceUsable(sourceDir: string, workspace: string): void {
  const sourceReal = realpathSync(sourceDir);
  const workspacePath = resolve(workspace);
  if (workspacePath === sourceReal || workspacePath.startsWith(`${sourceReal}${sep}`)) {
    throw new PaperRunError("The review workspace must be outside the source repository.");
  }
  if (existsSync(workspace) && lstatSync(workspace).isSymbolicLink()) {
    throw new PaperRunError("The review workspace cannot be a symbolic link.");
  }
  const staging = `${workspace}.paper-run-staging`;
  if (existsSync(staging)) {
    throw new PaperRunError(`Template staging path already exists: ${staging}`, {
      hint: "Remove or rename that path, then retry; paper-run will not delete an unrelated staging directory.",
    });
  }
  if (existsSync(workspace) && !isEmptyDir(workspace)) {
    throw new PaperRunError(`Review workspace is not empty: ${workspace}`, { hint: "Choose an empty or absent directory with --output." });
  }
}

export function detectEntrypoint(sourceDir: string, requested?: string): string {
  if (requested) {
    const candidate = resolve(sourceDir, requested);
    assertPathInside(sourceDir, candidate);
    if (!existsSync(candidate) || !statSync(candidate).isFile() || !candidate.endsWith(".tex")) {
      throw new PaperRunError(`TeX entrypoint not found: ${requested}`);
    }
    return candidate;
  }
  const texFiles = listSourceFiles(sourceDir).filter((path) => path.endsWith(".tex"));
  const candidates = texFiles.filter((path) => {
    const content = readFileSync(join(sourceDir, path), "utf-8");
    return /(^|\n)\s*\\documentclass(?:\[[^\]]*\])?\s*\{/m.test(stripTexComments(content));
  });
  if (candidates.length === 1) return join(sourceDir, candidates[0]!);
  if (candidates.length === 0) throw new PaperRunError("Could not find a TeX entrypoint containing \\documentclass.", { hint: "Pass --entry with the main .tex file relative to the source directory." });
  throw new PaperRunError(`Multiple TeX entrypoints found: ${candidates.join(", ")}`, { hint: "Pass --entry to select the manuscript to review." });
}

export function inspectReviewSource(
  sourceDir: string,
  entrypoint: string,
  files = listSourceFiles(sourceDir),
): ReviewSourceInspection {
  const fileSet = new Set(files);
  const sourceGraph: string[] = [];
  const visited = new Set<string>();

  const visit = (file: string) => {
    if (visited.has(file) || !fileSet.has(file)) return;
    visited.add(file);
    sourceGraph.push(file);
    const content = stripTexComments(readFileSync(join(sourceDir, file), "utf-8"));
    const directory = dirnamePosix(file);
    for (const match of content.matchAll(/\\(?:input|include|subfile)\s*\{([^}]+)\}/g)) {
      const raw = match[1]!.trim();
      const candidate = toPosix(join(directory, raw.endsWith(".tex") ? raw : `${raw}.tex`));
      visit(candidate);
    }
  };
  visit(entrypoint);

  const byExtension = (extensions: readonly string[]) => files.filter((file) => extensions.some((ext) => file.toLowerCase().endsWith(ext)));
  return {
    entrypoint,
    sourceGraph,
    bibliography: byExtension([".bib"]),
    figures: byExtension([".pdf", ".png", ".jpg", ".jpeg", ".eps", ".svg"]),
    tables: files.filter((file) => /(^|\/)(tables?|tabs?)(\/|$)/i.test(file) || /table/i.test(basenamePosix(file))),
    styles: byExtension([".sty", ".cls", ".bst"]),
    buildFiles: files.filter((file) => /(^|\/)(makefile|latexmkrc|tectonic\.toml|\.github\/workflows\/[^/]+)$/i.test(file)),
    evidenceFiles: files.filter((file) => /(^|\/)(experiments?|results?|evaluation|eval)(\/|$)/i.test(file) || /(^|\/)(experiments?|results?)\.(md|json|csv|tsv)$/i.test(file)),
  };
}

function copyPaperSource(sourceDir: string, paperDir: string): string[] {
  validateSourceLinks(sourceDir);
  for (const entry of readdirSync(sourceDir)) {
    if (EXCLUDED_SOURCE_ENTRIES.has(entry)) continue;
    cpSync(join(sourceDir, entry), join(paperDir, entry), { recursive: true, dereference: false });
  }
  return listSourceFiles(sourceDir);
}

function validateSourceLinks(sourceDir: string, current = sourceDir): void {
  for (const entry of readdirSync(current)) {
    if (current === sourceDir && EXCLUDED_SOURCE_ENTRIES.has(entry)) continue;
    const path = join(current, entry);
    const stat = lstatSync(path);
    if (stat.isSymbolicLink()) throw new PaperRunError(`Symbolic links are not supported in an imported paper repo: ${path}`);
    else if (stat.isDirectory()) validateSourceLinks(sourceDir, path);
    else if (!stat.isFile()) throw new PaperRunError(`Special files are not supported in an imported paper repo: ${path}`);
  }
}

function listSourceFiles(sourceDir: string, current = sourceDir): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(current).sort()) {
    if (current === sourceDir && EXCLUDED_SOURCE_ENTRIES.has(entry)) continue;
    const path = join(current, entry);
    const stat = lstatSync(path);
    if (stat.isDirectory()) files.push(...listSourceFiles(sourceDir, path));
    else if (stat.isFile()) files.push(toPosix(relative(sourceDir, path)));
    else throw new PaperRunError(`Special files are not supported in an imported paper repo: ${path}`);
  }
  return files;
}

function assertPathInside(root: string, path: string): void {
  const rel = relative(resolve(root), resolve(path));
  if (rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) throw new PaperRunError(`Paper source contains a path outside its repository: ${path}`);
}

function stripTexComments(content: string): string {
  return content.split("\n").map((line) => line.replace(/(^|[^\\])%.*/, "$1")).join("\n");
}

function writeReviewContext(
  workspace: string,
  source: string,
  inspection: ReviewSourceInspection,
  files: string[],
  paperDigest: string,
): void {
  ensurePaperRunDir(workspace);
  writeFileSync(join(workspace, PAPER_RUN_DIR, "review-source.json"), `${JSON.stringify({ schema_version: "paper-run-review-source-v1", source, ...inspection, paperDigest, imported_at: new Date().toISOString(), files: files.sort() }, null, 2)}\n`);
  writeFileSync(join(workspace, "BRIEF.md"), `# Independent manuscript review\n\n## Objective\n\nReview the imported manuscript without editing it.\n\n## Source\n\n- Entrypoint: \`paper/${inspection.entrypoint}\`\n- TeX source graph: ${inspection.sourceGraph.length} file(s)\n- Imported files: ${files.length}\n- Evidence coverage: only files copied into \`paper/\` are available; missing experimental records or external references must be reported as not assessable.\n`);
  writeFileSync(join(workspace, "PAPER.md"), `# Paper\n\n## Paper identity\n\nImported manuscript; identity is not normalized automatically.\n\n## What readers should believe\n\nThe reviewer must assess only claims stated in the imported manuscript.\n\n## Unresolved\n\n- External paper contracts were not available during transfer.\n- See .paper-run/review-source.json for the detected source graph and coverage.\n`);
  writeFileSync(join(workspace, "EXPERIMENTS.md"), `# Experiments\n\n## Experiment overview\n\nImported experiment/evaluation files are listed in .paper-run/review-source.json.\n\n## Claim-evidence bindings\n\nNot normalized during report-only transfer; assess the imported manuscript and available files directly.\n`);
  writeFileSync(join(workspace, "REFERENCES.md"), `# References\n\n## Imported bibliography\n\nBibliography files are listed in .paper-run/review-source.json.\n`);
}

async function initializeReviewRepository(workspace: string, version: string, mode: Mode, model?: string): Promise<void> {
  await execa("git", ["init"], { cwd: workspace });
  await execa("git", ["add", "-A"], { cwd: workspace });
  await execa("git", ["commit", "-m", "Initialize isolated manuscript review workspace"], { cwd: workspace });
  await initializeHarnessTrust(workspace, version);
  const runId = generateRunId();
  const branch = `${GIT.runBranchPrefix}${runId}`;
  const now = new Date().toISOString();
  const plan = createRunPlan("review-report");
  const state: RunState = { schema_version: "paper-run-v1", run_id: runId, run_branch: branch, mode, current_stage: "bootstrap", stage_status: "completed", started_at: now, updated_at: now, template_version: version, plan };
  writeRunState(workspace, state);
  writeGatePolicy(workspace, generateGatePreset(mode));
  writeStageHistory(workspace, { schema_version: "paper-run-stage-history-v1", stages: [{ stage_id: "bootstrap", status: "completed", started_at: now, completed_at: now, commit_sha: "prepared" }, ...plan.skipped.map((item) => ({ stage_id: item.stage, status: "skipped" as const, started_at: now, completed_at: now, commit_sha: "planned", skip_reason: item.reason }))] });
  await installAdapter(workspace, model !== undefined ? { model } : {});
  await createRunBranch(runId, workspace);
  await commitCheckpoint({ stageId: "bootstrap", status: "completed", runId, mode, templateVersion: version }, workspace);
}

function parseMode(value: string): Mode {
  if ((MODES as readonly string[]).includes(value)) return value as Mode;
  throw new PaperRunError(`Invalid mode "${value}".`, { hint: `Must be one of: ${MODES.join(", ")}` });
}

function reportPrepared(result: ReviewWorkspaceResult): void {
  log.blank();
  log.success("Isolated review workspace prepared.");
  printKeyValues([["Workspace", result.workspace], ["Entrypoint", `paper/${result.entrypoint}`], ["Imported files", String(result.files.length)], ["Plan", "review-report (no revision)"]]);
}

function toPosix(path: string): string {
  return sep === "/" ? path : path.split(sep).join("/");
}

function dirnamePosix(path: string): string {
  const index = path.lastIndexOf("/");
  return index < 0 ? "." : path.slice(0, index);
}

function basenamePosix(path: string): string {
  const index = path.lastIndexOf("/");
  return index < 0 ? path : path.slice(index + 1);
}
